# Configuração de Build para um site Vite
[build]
  # 1. Comando para construir o site Vite
  command = "npm run build"
  
  # 2. Pasta de saída do Vite (onde o site estático fica)
  publish = "dist"

# Configuração das Funções Serverless (Backend)
[functions]
  # 3. Pasta *fonte* das suas funções. O Netlify vai encontrá-las
  # e compilá-las automaticamente.
  directory = "netlify/functions"
  
  # --- ADICIONE ESTAS DUAS LINHAS ---
  # Define o 'bundler' (empacotador)
  node_bundler = "esbuild"
  # Diz ao Netlify para não tentar 'empacotar' o stripe, mas sim usá-lo
  external_node_modules = ["stripe"]
